### PR TITLE
fix for issue #480: handling min_delay in neuron

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
@apdavison : Could you take a look whether this is an acceptable fix for issue #480 . Thanks.

Basically rearranged some of the code so that 'auto' is handled before the current error arises. It solves the current issue, and cleared all the tests. But not sure if it affects any other parts of the (untested) code.

### CODE REVIEW

**Comment by apdavison** [comment]
I don't think this solves the problem. The issue is that the user could later create a connection with a shorter delay, and this would then presumably trigger an Exception, or put the simulation into an inconsistent state.

Looking at the example, the statement 
```python
syn = sim.StaticSynapse(weight=0.05)
```
should raise an `InvalidParameterValueError` something like "Neither delay nor min_delay has been specified".

**Comment by appukuttan-shailesh** [comment]
Would it be feasible to assign a default value for `delay` or `min_delay`? The changes could possibly be incorporated inside `_get_minimum_delay()` in `neuron/standardmodels/synapses.py`?

**Comment by appukuttan-shailesh** [comment]
Would it be feasible to assign a default value for `delay` or `min_delay`? The changes could possibly be incorporated inside `_get_minimum_delay()` in `neuron/standardmodels/synapses.py`?

Considering that the code works for NEST and Brian, wasn't sure why we can't make it run (instead of raising an error ) in NEURON.

**Comment by apdavison** [comment]
PyNN used to have a default value for `min_delay` of 0.1 ms. However, this often led to inefficient simulations, since smaller min delay means that MPI communication has to happen more frequently.

The code works for NEST and Brian because it uses a simulator-specific default in each case.

We *could* make this code run, but after reflecting a bit, I don't think we *should* make it run, and in fact we should modify Brian and NEST so that they also raise an Exception.

The convention in PyNN is that if you don't specify a delay for a connection, the default value is the global `min_delay`. However, in this example, `min_delay` is undefined, so it is not clear what value to use. We could have a default `delay` for all synapses. However, we then have to handle the case where a user-specified `min_delay` is larger than the default delay; it risks getting rather complex and confusing for the user.

It is easy for the user to fix this error: either specify `min_delay`, or specify an explicit `delay` parameter. The latter is probably what they ought to do.

**Comment by appukuttan-shailesh** [comment]
Thanks for elaborating on the matter. I have a much better understanding of the problem now.

**Pull request closed without merging**
