### PR TITLE
Updated NEST functions that have been moved to submodules

### PR DESCRIPTION
**Pull request by hakonsbm**
With nest/nest-simulator#1058, included in the NEST 2.18.0 release, parts of PyNEST was reorganized, leading to some functions only being accessible through a submodule. With this PR affected calls, i.e. `sli_func()`, `sli_run()` and `NESTError`, have been updated.

### CODE REVIEW

**Comment by apdavison** [comment]
I've updated the nest-dev branch, which was quite out of date. Please could you push a new commit to this PR (e.g., add yourself to the AUTHORS file) to run the tests again?

**Comment by apdavison** [comment]
This is looking good. I see only one error in the Travis log, which should be fixed by adding "post_trace" to the "ignore" list in [nest/cells.py](https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/nest/cells.py#L27) 

Please could you also update references to NEST 2.16 in the doc folder?

**Comment by hakonsbm** [comment]
@apdavison I also changed the `SimpleStochasticSynapse` model to `bernulli_synapse`. Hopefully that is correct.

Looks like Travis complains about Brian now.

**Comment by apdavison** [comment]
Many thanks @hakonsbm 

I'm not sure if `bernoulli_synapse` is identical to the model provided by PyNN, but at least it passes the test. I'll take a closer look after merging this PR but before releasing the new version of PyNN.

The Brian test is clearly nothing to do with this PR, so I will merge this and then look at that later.

**Pull request merged**
