### PR TITLE
Updates for new NEST 3.0 API

### PR DESCRIPTION
**Pull request by clinssen**

### CODE REVIEW

**Comment by clinssen** [comment]
Looks like Travis weren't kidding this time when they said that travis-ci.org would cease operations on June 15th. @apdavison: could you perhaps [migrate to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/), or do you have plans to migrate to GitHub Actions?

**Comment by clinssen** [comment]
It seems that the CI is no longer running when I do a push on this PR branch. Clicking on the last CI run, the URL still points to travis-ci.org, so could it be that the GitHub integration with the new travis-ci.com is not working correctly?

**Comment by pgleeson** [comment]
FYI I took the time to migrate many of our repos from travis-ci.org to .com, and they worked nicely for a while, but have now stopped. Think it's something to do with limited free hours/units associated with a non paid account. It might be worth taking the time to move to Github actions sooner rather than later...

**Comment by clinssen** [comment]
Closing as this is superseded by #724.

**Pull request closed without merging**
