### PR TITLE
Rename aux.py to auxiliary.py to make pynn works on Windows machines.

### PR DESCRIPTION
**Pull request by ChihweiLHBird**
Since `aux` is a reserved file name on Windows, aux.py is not allowed on Windows machine and can lead to an error. Simply change the name of the file from `aux.py` to `auxiliary.py` can fix it.

Microsoft Documents: https://docs.microsoft.com/de-de/windows/win32/fileio/naming-a-file
Similar change done for another python package: https://github.com/TUD-RST/symbtools/issues/5
Related issues: https://github.com/NeuralEnsemble/PyNN/issues/666, https://github.com/NeuralEnsemble/PyNN/issues/446

### CODE REVIEW

**Comment by ChihweiLHBird** [comment]
Python 2.7 and 3.3 tests failed but Python 3.6 test works fine. Since 2.7 and 3.3 are out of official support period, I would suggest removing Python 2.7 and 3.3 and add 3.5, 3.7, 3.8 for testing.

**Comment by apdavison** [comment]
The test failure for 2.7 is one which is known to fail occasionally as it involves a statistical test; it has nothing to do with the PR. The failure for 3.3 is in uploading coverage stats, the tests actually all pass.

(Agreed on updating the test matrix to more recent versions of Python; we plan to do this soon).

**Comment by macknight** [comment]
install tf-encrypted failed. how to rename? I can't even find the fold.

ERROR: The tar file (C:\Users\xx\AppData\Local\Temp\pip-unpack-plha6gd0\tf-encrypted-0.9.1.tar.gz) has a file (C:\Users\xx\AppData\Local\Temp\pip-install-bj8xrdtv\tf-encrypted_08c1f7c5ab8c46a19975b7aaec907caf\tf_encrypted/operations/aux) trying to install outside target directory (C:\Users\xx\AppData\Local\Temp\pip-install-bj8xrdtv\tf-encrypted_08c1f7c5ab8c46a19975b7aaec907caf)

**Comment by codenum137** [comment]
@macknight 
hi, I get into the same problem when installing tf-encrypted, have you fixed it? how? thx

**Comment by apdavison** [comment]
@macknight @codenum137 I don't think your issue is relevant PyNN

**Pull request merged**
