### PR TITLE
Added `SpikeSourceGamma` model.

### PR DESCRIPTION
**Pull request by apdavison**
with implementations in NEST and NEURON backends, and unit test. cf #386 

**NEST**
test_spikesourcegamma_pynn nest

**NEURON**
test_spikesourcegamma_pynn neuron

Note that the distribution for NEST is slightly distorted for high rates, since spikes can only occur on time-step boundaries.

### CODE REVIEW

**Comment by apdavison** [comment]
@Huitzilo can you take a look?

**Comment by apdavison** [comment]
@markovg any comments? By the way, any chance of updating the inhomogeneous gamma process NEST model from your thesis and getting it into NEST master?

**Comment by Huitzilo** [comment]
@apdavison Thanks for implementing this!

**Comment by apdavison** [comment]
In the absence of further comments, merging this now.

**Pull request merged**
