### PR TITLE
This Pull Request fixes #377

### LINKED ISSUE #377: PyNN exhausts NEST 2.6/2.8 synapse model storage
Running code along the line of

    for i in xrange(257):
        sim.Projection(pop[0], pop[i], self.sim.FromListConnector([(0, 0, 0.03, 0.1)]))

causes the following NEST exception

    Oct 11 01:08:09 ConnectionManager::copy_synapse_prototype [Error]: 
    CopyModel cannot generate another synapse. Maximal synapse model count of 
    255 exceeded.

Backtrace:

      File "./run.py", line 55, in <module>
        output = sim.run(topo)
      File "/home/andreas/hbp-pynnless/pynnless/pynnless.py", line 786, in run
        self.sim.FromListConnector(descrs))
      File "/usr/lib/python2.7/site-packages/pyNN/nest/projections.py", line 48, in __init__
        self.nest_synapse_model = self.synapse_type._get_nest_synapse_model("projection_%d" % Projection._nProj)
      File "/usr/lib/python2.7/site-packages/pyNN/nest/synapses.py", line 45, in _get_nest_synapse_model
        nest.CopyModel(self.nest_name, label, synapse_defaults)
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/hl_api.py", line 154, in stack_checker_func
        return f(*args, **kwargs)
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/hl_api.py", line 591, in CopyModel
        sr("/%s /%s 3 2 roll CopyModel" % (existing, new))
      File "/home/andreas/.local/lib64/python2.7/site-packages/nest/__init__.py", line 81, in catching_sli_run
        raise hl_api.NESTError("{0} in {1}{2}".format(errorname, commandname, message))

It seems like PyNN unnecessarily causes the creation of a new synapse model, although the same synapse parameters are used for all created synapses, exhausting the limited synapse model storage in NEST.

This bug affects PyNN 0.8 and NEST 2.6.0 and 2.8.0. The bug does not occur with NEST 2.4.2.

### PR DESCRIPTION
**Pull request by jschuecker**
This should not be merged until nest/nest-simulator#158 is merged.

### CODE REVIEW

**Comment by apdavison** [comment]
Our policy is that the PyNN master branch should always work with the most recent *released* version of NEST, so once NEST 2.10 is released we can merge this into master. In the meantime, I could create a `nest-dev` branch for people wishing to use PyNN master with NEST master, and merge your fix into that. What do you think?

**Comment by jschuecker** [comment]
@apdavison, that sounds good to me!

**Comment by mschmidt87** [comment]
I just added 2 commits that fix the unittests of NEST in pyNN if run against NEST 2.10.
However, the Travis CI system fails. As far as I can see, there are two problems:
1. Travis tries to download the release version of NEST with a false URL. 
2. Travis tries to download NEST 2.6.0, but the newest release version is NEST 2.10.

The URL in travis should thus be changed to
https://github.com/nest/nest-simulator/releases/download/v2.10.0/nest-2.10.0.tar.gz

**Comment by apdavison** [comment]
Hi @jschuecker, please can you re-open this pull request against the nest-dev branch? (I know that NEST 2.10 has already been released, but I'd like to test the workflow).

**Comment by jschuecker** [comment]
@apdavison, I have re-opened the pull request against the nest-dev branch.

**Comment by apdavison** [comment]
Closed in favour of #392

**Pull request closed without merging**
