### PR TITLE
Generalized integrate-and-fire model

### PR DESCRIPTION
**Pull request by apdavison**
for NEST and NEURON backends. Brian implementation still needed.

Requires development version of NEST (Github master branch).

Only simple, cond-exp synapses for now.

### CODE REVIEW

**Comment by pgleeson** [comment]
FYI: GLIF models from the Allen Institute Cell Types Database project have been converted to LEMS (for eventual incorporation into NeuroML2) here: https://github.com/OpenSourceBrain/AllenInstituteNeuroML/tree/master/CellTypesDatabase/models/GLIF

**Comment by apdavison** [comment]
@croessert does this look ok to you?

**Comment by apdavison** [comment]
@pgleeson Thanks for the info

**Comment by apdavison** [comment]
In the absence of further comments, merging this now.

**Pull request merged**
