### PR TITLE
Replacing source_id by channel_id as multiprocessed simulation are crashing on this line

### PR DESCRIPTION
**Pull request by RCagnol**
I noticed that the new version of neo is using channel_id to get the id of neurons of the SpikeTrainList object. Multiprocessed nest simulations are crashing on this line of code, replacing channel_id by source_id there seems to solve this issue.

### CODE REVIEW

**Comment by apdavison** [comment]
`channel_id` appears nowhere else in the PyNN codebase, whereas `source_id` appears in several places. This makes me think that a more extensive PR might be needed.

**Comment by RCagnol** [comment]
Indeed, I didn't identify correctly the source of the problem when creating this fix. In the _get_current_segment() method, when the spike times are contained in a tuple, the SpikeTrainList object is created (here: https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/recording/__init__.py#L289 ) without any annotations corresponding to the source_id. I'll update the PR.

**Comment by apdavison** [comment]
Seems to be that the tests are now using numpy 1.24, which removes `numpy.bool`

see https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations

**Comment by RCagnol** [comment]
Thanks for the answer. At first I didn't think this that the presence of 'np.bool' was the source for almost all the Nest tests failing, but I just noticed that Nest 3.3 faces the same problem: https://github.com/nest/nest-simulator/pull/2571 
Therefore the tests would still fail (beside the workflow 'Test on windows-latest with Python 3.8' which skips the NEST tests), even after replacing 'np.bool' by 'bool' in PyNN. 
So probably the solution would be to use numpy 1.23 in the workflow until Nest 3.4 comes out?

**Comment by apdavison** [comment]
Hi @RCagnol I extended your solution, and made a new PR, #797.

**Pull request closed without merging**
