### PR TITLE
WIP: testing Sonata import

### PR DESCRIPTION
**Pull request by pgleeson**
@apdavison Some minor changes while testing Sonata

- You had a previous commit/issue showing the results of the import of the 300 intfire cell network. Could you point to it again?
- Is there any reason why you don't use the index (rather than a native gid?) of the cell in the population for the node_id in the exported network. Probably the node_ids don't have to start at 0 a/c the spec, but it would be useful for other importing applications (of the generated Sonata) that assume they will...

image

### CODE REVIEW

**Comment by pgleeson** [comment]
@apdavison Any pointers to running the 300 intfire cell network in PyNN, as mentioned above, would be appreciated.

**Comment by apdavison** [comment]
@pgleeson I just saw the "WIP" prefix, which I guess means I shouldn't have merged this yet? Sorry about that.

**Comment by apdavison** [comment]
This is the script I use to run the 300 intfire example:
```python
from pyNN.serialization import import_from_sonata, load_sonata_simulation_plan
import pyNN.neuron as sim

simulation_plan = load_sonata_simulation_plan("simulation_config.json")
simulation_plan.setup(sim)
net = import_from_sonata("circuit_config.json", sim)
simulation_plan.execute(net)
```

(I put this in a script `run_pyNN.py`, in the SONATA `examples/300_intfire` directory).

**Comment by apdavison** [comment]
> * Is there any reason why you don't use the index (rather than a native gid?)

This of course needs to be changed (I may have changed it already, I have a vague memory of doing so). It was a temporary hack.

In general, the implementation needs to be updated with the recent changes to the spec, then there are a number of things I know are incomplete, and most likely a bunch of edge cases I haven't thought about. 

Our institute has its every-5-years evaluation the second week in January. I probably won't be able to do much on this until that's over with.

**Comment by apdavison** [comment]
The results of running the example with PyNN were shown here: https://github.com/AllenInstitute/sonata/pull/32#issuecomment-428118756

**Comment by pgleeson** [comment]
Thanks, that works for me here. Will test more examples in new year.

**Pull request merged**
