### PR TITLE
Update brian imports to use brian2

### PR DESCRIPTION
**Pull request by sanjayankur31**
All the brian documentation says `import brian2`, so that's what we
should use too.

https://brian2.readthedocs.io/en/stable/resources/tutorials/1-intro-to-brian-neurons.html

### CODE REVIEW

**Comment by apdavison** [comment]
I wish it was so simple. Unfortunately, Brian 2 is not 100% backwards compatible with Brian 1, or at least, PyNN relies on internal implementation details of Brian 1. @appukuttan-shailesh is working on a Brian 2 backend.

**Comment by sanjayankur31** [comment]
Ugh, I hadn't realised that. So, if one wants to use pynn with brian, they also need to have brian1 installed?

**Comment by sanjayankur31** [comment]
If so, we should probably document this. Folks installing brian2 from source will be in for a couple of surprises otherwise :/

**Comment by sanjayankur31** [comment]
Ah, it's in the docs. Sorry about that:

http://neuralensemble.org/docs/PyNN/installation.html?highlight=brian

**Comment by appukuttan-shailesh** [comment]
No definite timeline as of now, but hoping for an initial release in 2-3 months.
(been wanting to redirect time and efforts towards this since a long time!)

**Comment by sanjayankur31** [comment]
If there's some sort of task list of what needs to be done, a few of us could help?

**Comment by appukuttan-shailesh** [comment]
@sanjayankur31 : Thanks! That could be helpful. I will try to upload a minimal working version (that I have started on) in the next 2 (max 3?!) weeks, so that we all have something to build on. Once that is done, I will upload a list of sub-tasks that need to be taken up. I would be happy to have you and others pick from these and contribute.

**Comment by sanjayankur31** [comment]
That would be brilliant. I'm sure I (and others) would be happy to help!

**Comment by laurentperrinet** [comment]
I would be glad helping testing that! 

(btw, why is that issue closed?)

**Pull request closed without merging**
